### PR TITLE
Add constants for nl_langinfo(3).

### PR DESCRIPTION
**Pull request by nirvdrum**

### CODE REVIEW

**Comment by nirvdrum** [comment]
@headius I may have merged this a bit prematurely. I'm a bit concerned that Linux & Mac have different values for the constants. I can probably get access to a FreeBSD machine to generate the constants there as well. But do we have a semi-reasonable way to ensure the native platforms have accurate values? I recall someone was working on a KVM system for that, but I'm not sure if got to the point of being usable.

**Comment by nirvdrum** [comment]
I was able to do the FreeBSD one fairly easily. That's been pushed separately.

**Comment by headius** [comment]
@nirvdrum Generally the constant values should be generated by the provided scripts, rather than coded by hand. There might be some variation within a given platform+OS but it's unlikely.

**Comment by headius** [comment]
BTW, please tag all merged PRs and fixed issues with a release milestone, just like in JRuby.

**Comment by nirvdrum** [comment]
Sorry about the milestones -- I'll do that in the future.

I'm generating the files with the provided scripts, but when missing for a platform it jnr-constants falls back to the fake one. Usually the fake one works because there's really limited variation in values across platforms for most values. In this case, the Linux & BSD/Mac values are quite different, so any missing platform relying on the fake values is likely to fail.

**Pull request merged**
