### PR TITLE
Update Linux constants

### PR DESCRIPTION
**Pull request by aughr**
I followed the README to get SO_REUSEPORT to be defined in Linux (as per #8), but that did a whole lot more than I was expecting. If you want me to close this out and add it manually, I'm fine with that too.

### CODE REVIEW

**Comment by aughr** [comment]
@headius

**Comment by headius** [comment]
The changes look ok to me but yeah, a lot of stuff got updated I wouldn't have expected. What Linux was this on?

**Comment by nirvdrum** [comment]
A lot of this is changes to the generated timestamp and updates to make all literals long values (the existing files must've been generated before that was added to the Rakefile). Unfortunately, that does make the diff a lot noisier. I'd like to see which values changed more easily.

**Comment by headius** [comment]
I agree with @nirvdrum. Can you force-push this as just manually adding that constant, and perhaps put the generated update in a separate commit?

**Comment by aughr** [comment]
@headius Sorry for the quite long delay. This is in two commits now: a manual one-liner and then the full regeneration.

**Comment by aughr** [comment]
Looks like an unrelated Javadoc generation failure on openjdk6.

**Comment by brettwooldridge** [comment]
@aughr @headius Anything happening with this?

**Comment by chrisvest** [comment]
The addition of SO_REUSEPORT is not the only thing that changes.

The following constants are also modified one way or another by the regeneration, as far as I can tell:

AF_ISDN, AF_MAX, PF_ISDN, PF_MAX, F_GETLK, F_SETLK, F_SELKW, FAPPEND, FASYNC, FFSYNC,
FNONBLOCK, FNDELAY, O_SYNC, O_FSYNC, O_NOFOLLOW, O_DIRECTORY, O_TMPFILE, O_CLOEXEC,
RLIM_*, RLIMIT_RTTIME...

Any maybe others.

**Comment by headius** [comment]
This is superseded by #33. See also #41 which made repairs to the regeneration logic. Thank you for your help though!

**Pull request closed without merging**
