### PR TITLE
Attempt to fix and normalize generation across platforms.

### PR DESCRIPTION
**Pull request by headius**
The primary change here is to stop using the sorted list.
The regen:xplatform does not sort, and just uses the order
provided in the .rb files. Sorting in the platform files
appears to have been added only to determine min/max values for
each constant set.

This change was needed because the sort was broken for
posix_fadvise constants on MacOS since fcntl required ok but none
of those constants exist. The resulting list was empty, got sorted,
and then sorted.first/last were nil for min/max. Fixing that led to
issues because all platforms will have some missing values
(.value = nil) so the sort by value must be constrained to min/max
purposes.

This will cause most platforms to regenerate with rather large
diffs, since the numeric ordering is now replaced with the order
from the gen/const files, but this should be a one-time hit.

### CODE REVIEW

**Comment by headius** [comment]
@ahorek @enebo @stakach We need to discuss this. I was unable to regenerated on MacOS because of a PR in 2016 that added constants for posix_fadvise. Those constants don't exist on MacOS, but fcntl.h does, so they were breaking the generation process mostly because of the sorting and min/max logic.

I did the regenerations as three separate PRs. @ahorek I have not reviewed your regeneration but once we are happy with *this* PR I'm sure yours will need to be regenerated as well.

**Comment by headius** [comment]
@ahorek You also appear to have had the issue with the cross-platform Errno.java getting massively altered. That may be unavoidable...it appears a bunch of errno names were spliced into the .rb files, which means that the Java enum values will no longer be in the correct places.

Or we might be able to figure out what the original order was and move the spliced in values to the end of the .rb files.

There's no really good way to fix this since we can't impose a total ordering on these files. There will always be new values coming in. The least-impact right now would be fixing Errno.rb to preserve the existing values in original order and move all the new values to the end.

**Comment by ahorek** [comment]
@headius I took errno constants from
https://github.com/ruby/ruby/blob/4444025d16ae1a586eee6a0ac9bdd09e33833f3c/defs/known_errors.def

The change will definetely break fake constants, but do we need to preserve compatibility here? If something depends on the enum order we should find a better way to map those values.

I've included your change to my PR's and reverted files that wasn't changed to reduce diff.

**Comment by headius** [comment]
@ahorek I think I've dealt with the Errno issues in #44 by restoring the .java ordering for the ones already there and moving all the other values to the end. The new xplatform version only *adds* errnos, rather than reordering them, which should preserve binary compatibility with previous releases.

I think we're good to go here.

**Comment by ahorek** [comment]
thanks, let me know when it's ready

**Comment by headius** [comment]
@ahorek One more time, I promise :-) With your errno test fix and some final tweaks I believe everything is working properly.

**Comment by headius** [comment]
@ahorek Oh, I believe you should be able to get away with only regenerating the `platform` files. You can confirm that the others don't make any changes, though. They'll update timestamps, so if there's no changes there's no need to have them in your PRs.

**Comment by headius** [comment]
@aploese Sounds like a good idea! 😁 

While fixing the problems with the generator, we started to wonder if there might be a better way. The current system seems a tad overcomplicated, and caches nothing from the different platforms. I would wonder about licensing of keeping those files in our repo, but we can look into that.

We do not have much experience with preprocessed headers; I am a C hobbyist at best. Does this preprocessed output have anything specific to gcc or is it useful to us across C compilers?

**Comment by headius** [comment]
@aploese Actually, I think you should open a separate issue and we can discuss it there!

**Pull request merged**
