### PR TITLE
generate all architecture constants on x86

### PR DESCRIPTION
**Pull request by merore**
I built [docker image](https://github.com/merore/jnr-multiarch-env) for jnr to run and test with multiarch on x86. `autogen.sh` can use this image to generate all architecture constants on x86.

You must add `bitfmt_misc` for system before running this scripts. A simple way is to run `docker run --rm --privileged multiarch/qemu-user-static`

Instructions:
`./scritps/autogen.sh` regenerate all platform constants
`./scriptes/autogen.sh aarch64` regenerate constants for the specified platform

In the future, I plan to use this images to test of jnr-posix, etc.

### CODE REVIEW

**Comment by headius** [comment]
Very nice! Have you seen the qemu + docker rig for jffi in https://github.com/jnr/jffi/pull/90? I think we can find some synchronicity here and get all Linux platforms building and testing across the whole JNR stack based on your work and the work by @TobiX.

Thank you for jumping into this!

**Comment by TobiX** [comment]
Docker now has official GitHub actions, which should make the process much less fiddly: https://github.com/docker/setup-qemu-action

**Comment by merore** [comment]
@TobiX 
Hello, I have some problems this this work.
[native-linux.yaml](https://github.com/jnr/jffi/blob/master/.github/workflows/native-linux.yml) why does this script work? I need at least two steps to run other archs container on x86.  (1) inject bitfmt_misc (2) map qemu-static into containers with `docker run -v /usr/bin/qemu-aarch64-static: /usr/bin/qemu-aarch64-static debian:10`

**Comment by TobiX** [comment]
@merore That GitHub Action does work because since Kernel 4.8 you don't need to pass the interpreter into the container for binfmt_misc to do its magic (https://github.com/torvalds/linux/commit/948b701a607f123df92ed29084413e5dd8cda2ed) IF it was configured correctly.

In Debian-based OSes this "configured correctly" happens since `qemu-user-static` 4.2something AFAICS, so you need Ubuntu 20.04 or Debian 11 for this to work with the system packages...

**Comment by merore** [comment]
> @merore That GitHub Action does work because since Kernel 4.8 you don't need to pass the interpreter into the container for binfmt_misc to do its magic ([torvalds/linux@948b701](https://github.com/torvalds/linux/commit/948b701a607f123df92ed29084413e5dd8cda2ed)) IF it was configured correctly.
> 
> In Debian-based OSes this "configured correctly" happens since `qemu-user-static` 4.2something AFAICS, so you need Ubuntu 20.04 or Debian 11 for this to work with the system packages...

Thank you for your repley! I will continue to do this work.

**Comment by headius** [comment]
Any updates here? Sounded like there was more work coming.

**Pull request closed without merging**
